### ISSUE TITLE
Question about Edge runtime

### ISSUE THREAD

**Issue by zomars** [nikolovlazar/nextjs-clean-architecture#7]
Quoting the README:

> There is a catch here - You can't use the Edge runtime. That means [Middleware](https://nextjs.org/docs/app/building-your-application/rendering/edge-and-nodejs-runtimes#use-cases) will not work. This is because of [inversify](https://inversify.io/). Inversify only supports the Node runtime.

Does this means that we cannot use injected dependencies in the Edge runtime or that we cannot use the Edge runtime at all?

**Comment by ArmmGh** [comment]
Yes, we cannot use, but there is an alternative suggested by @nikolovlazar which isn't using reflection and should work
[Typed-Inject](https://www.npmjs.com/package/typed-inject#usage)

**Comment by nikolovlazar** [comment]
Sorry I didn't see this until today @zomars. And yes, the typed-inject library should be fine to be used in the middleware. I haven't tried it yet, but on paper it seems that it should work.

**Comment by ArmmGh** [comment]
@zomars I’ve successfully migrated from Inversify to typed-inject, and it works seamlessly with middlewares and edge functions without any issues, if you need help feel free to reach out

Very simple example similar to @nikolovlazar's implementation with inversify 👇 
![image](https://github.com/user-attachments/assets/6d636650-4006-4c81-b2e7-87ba5f184d08)

**Comment by nikolovlazar** [comment]
That's awesome @ArmmGh! Do you have a repo? I tried `typed-inject` but couldn't make it work. I had trouble registering factories and dependencies. I did managed to achieve Edge runtime with `ioctopus` though: #11 . Take a look!

**Comment by ArmmGh** [comment]
@nikolovlazar I was also thinking to use `ioctopus` but tbh `typed-inject` more battle tested, and I need more long term solution for me.
I can't make the repo public but I can share the approach which is quite similar to yours with `inversify`

![image](https://github.com/user-attachments/assets/aa236361-c4e4-4e08-b501-cbcfb4ed31a7)

![image](https://github.com/user-attachments/assets/0531a5dc-b356-44d5-806f-7d7a575f3a35)

**Comment by nikolovlazar** [comment]
@ArmmGh thank you! The challenge I faced was when trying to register conditionally (env variable) and with dependencies (service needs a repo, and vice versa).

If I break the chaining the type of the injector breaks, so I can't pass the injector and use it to resolve dependencies while registering other dependencies.

On the other hand, it didn't give me an instance of the injector through arguments when registering a factory, and that's where I got blocked. Can't pass it around, don't get it from the args, there's no way to conditionally register repos & services that also depend on other repos & services. Think auth service depends on users repo, and there are two versions of the service: mock and real implementation. I don't want to use the getInjection method inside the service to obtain the users repo. I want to leverage constructor injection so the code is cleaner.

Maybe I should've spent more time on it. However, I'm sticking with ioctopus because it works like a charm 😁

**Comment by ArmmGh** [comment]
> @ArmmGh thank you! The challenge I faced was when trying to register conditionally (env variable) and with dependencies (service needs a repo, and vice versa).
> 
> If I break the chaining the type of the injector breaks, so I can't pass the injector and use it to resolve dependencies while registering other dependencies.
> 
> On the other hand, it didn't give me an instance of the injector through arguments when registering a factory, and that's where I got blocked. Can't pass it around, don't get it from the args, there's no way to conditionally register repos & services that also depend on other repos & services. Think auth service depends on users repo, and there are two versions of the service: mock and real implementation. I don't want to use the getInjection method inside the service to obtain the users repo. I want to leverage constructor injection so the code is cleaner.
> 
> Maybe I should've spent more time on it. However, I'm sticking with ioctopus because it works like a charm 😁

I see, very valid points, my example is very simple and thats why not challenging
I might also need to migrate to `ioctopus` at some point if project grows and I also need conditional envs and  service<->repo dependency via cosntructor

**Comment by Evyweb** [comment]
The code I wrote for ioctopus is quite simple and can also be adjusted /improved according to your needs. Don't hesitate to make some suggestions and I will update it. At the end it is only 70 lines of code or something like that and can also serve as foundations for something more complex. My goal was to have something simple to use, easy to understand and working with middlewares and without any kind of magic behind the scene. Any idea on improvements @ArmmGh ?

**Comment by ArmmGh** [comment]
@Evyweb Thanks for the response.
I haven't checked the codebases deeply and just decided to choose `typed-inject` because of downloads, community etc and I needed to switch to something well tested asap until the project haven't grown.. 
But now I see your points and I think it is better to check codes as well and not to rely just on downloads, I will check `ioctopus` deeper and might switch to it until it is not too late. then I can come up with improvements if I have something in my mind and I'm always open to contribution in tools that I use!
